version: "3.9"

services:
  ingredient-service:
    build: ./ingredient-service
    container_name: ingredient-service
    ports:
      - "5000:5000"

  recipe-service:
    build: ./recipe-service
    container_name: recipe-service
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    container_name: ingredient-recipe-frontend
    ports:
      - "8080:80"
    depends_on:
      - ingredient-service
      - recipe-service